Map<String, String> englishLanguage = {
  'your_home_best_friend': 'Your Home\'s Best Friend',
  'get_your_home_services_done':
      'Get all your home services in one place: AC repair, plumbing, cleaning, electrical, and painting — just a tap away.',
  'get_started': 'Get Started',
  'skip': 'Skip',
  'choose_role': 'Choose Your Role Below',
  'select_an_option': 'Please Select An One Option To Start Your Journey',
  'join_as_user': 'Join As a User',
  'join_as_provider': 'Join As a Srvices Provider',
  'sign_in_to_account': 'Sign In Your Account',
  'welcome_back': 'Welcome Back! Please Enter Your Details.',
  'your_email': 'Your Email',
  'enter_your_email': 'Enter Your Email',
  'please_enter_your_email': 'Please Enter your Email',
  'password': 'Password',
  'enter_password': 'Enter Password',
  'please_enter_password': 'Please Enter Your password',
  'forgot_password': 'Forgot Password?',
  'sign_in': 'Sign in',
  'don\'t_have_account': 'Don’t have an account?',
  'sign_up': 'Sign up',
};
